// import './cours/1_nombres'
// import "./cours/2_saisie_clavier"
// import './exercices/1_exo_mru'
// import './cours/3_strings'
// import './exercices/2_exo_permutations2'
// import './exercices/3_exo_annee_naissance'
// import './cours/4_conditions'
// import './cours/5_conditions_multiples'
// import './cours/6_boucle_for'
// import './exercices/10_table_multi'
// import './cours/7_while'
import './cours/8_while_suite'
